[package]
name = "webrtc-sdp"
version = "0.3.0"
authors = ["Nils Ohlmeier <github@ohlmeier.org>"]
description = "This create parses strings in the format of the Session Description Protocol according to RFC4566. It specifically supports the subset of features required to support WebRTC according to the JSEP draft."
repository = "https://github.com/mozilla/webrtc-sdp"
readme = "README.md"
keywords = ["webrtc", "sdp", "jsep"]
categories = ["parsing", "network-programming"]
license = "MPL-2.0"

[badges]
travis-ci = { repository = "nils-ohlmeier/rsdparsa", branch = "master" }
codecov = { repository = "nils-ohlmeier/rsdparsa", branch = "master", service = "github" }

[features]
default = []
# serializability
serialize = ["serde", "serde_derive"]

[dependencies]
log = {version = "0.4.6"}
serde = {version = "1.0" , optional = true}
serde_derive = {version = "1.0" , optional = true}
url = {version="2.1.0"}

[dev-dependencies]
serde_json = {version = "1.0"}
